### ISSUE TITLE
Extension doesn't work on NameCheap.com

### ISSUE THREAD

**Issue by londondev77** [twofas/2fas-browser-extension#35]
When I try to use the extension on NameCheap.com, I get an alert to tell me to select the text field.  I am doing this so I assume maybe some kind of custom rule needs to be built into the extension to work in this case.

<img width="1092" alt="image" src="https://github.com/twofas/2fas-browser-extension/assets/1478538/63f18003-72c9-4357-b44e-997bd53e75dc">

**Comment by GrzegorzZajac000** [comment]
@londondev77 Thank you for reporting this bug. I will check that.

**Comment by GrzegorzZajac000** [comment]
@londondev77 I found the bug. It should be fixed in v1.6.0 ;)

**Comment by londondev77** [comment]
Wow, that was quick!

**Comment by GrzegorzZajac000** [comment]
@londondev77 Sorry for the delay, but besides fixing bugs, we added an important feature, and it took us a while ;) Version 1.6.0 has been uploaded to stores. It should be visible to users in the next few hours.

**Comment by londondev77** [comment]
I've just tested with 1.6.1 and unfortunately I'm still seeing the same issue :-(

**Comment by GrzegorzZajac000** [comment]
@londondev77 Sorry to hear that :( It should work on 1.6.0, but that version has some problems with performance. I will try to look into this one more time.

**Comment by GrzegorzZajac000** [comment]
@londondev77 I fixed both the problems with namecheap and the slowdown of some pages. I just released v1.6.2 to QA, which should make fixes to these issues.

**Comment by GrzegorzZajac000** [comment]
@londondev77 Sorry for slight delay, but we had few another problems. v1.6.2 was uploaded to stores. Should be available in near future for users. Thank you for patience ;)

**Comment by londondev77** [comment]
It works - thanks for sorting!
